# Generated by Django 2.0.1 on 2018-02-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDept',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=12)),
                ('condition', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('sample', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('hospital_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientWaittimes',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_month', models.IntegerField()),
                ('visit_day', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('wait_time', models.IntegerField()),
                ('immediacy', models.IntegerField()),
                ('painscale', models.IntegerField()),
                ('blinded_hospital_code', models.IntegerField()),
                ('metro_area', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UrgentCare',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=9)),
                ('user_time', models.TimeField()),
                ('user_date', models.DateField()),
            ],
        ),
    ]
