# Generated by Django 2.0.2 on 2018-02-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0004_auto_20180222_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentcare',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='urgentcare',
            name='lng',
            field=models.FloatField(),
        ),
    ]
