# Generated by Django 2.0.2 on 2018-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0005_auto_20180224_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=9)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
