# Generated by Django 2.0.2 on 2018-02-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0006_ziplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziplocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='ziplocation',
            name='zipcode',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
