# Generated by Django 2.0.2 on 2018-03-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0007_auto_20180225_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientWaittime',
        ),
    ]
